// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcppConstructBarcodeIndex
std::vector<std::vector<int>> rcppConstructBarcodeIndex(std::vector<std::string>& conDfBarcodes, std::vector<std::string> data2Barcodes);
RcppExport SEXP _scRepertoire_rcppConstructBarcodeIndex(SEXP conDfBarcodesSEXP, SEXP data2BarcodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string>& >::type conDfBarcodes(conDfBarcodesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type data2Barcodes(data2BarcodesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppConstructBarcodeIndex(conDfBarcodes, data2Barcodes));
    return rcpp_result_gen;
END_RCPP
}
// rcppConstructConDfAndParseTCR
Rcpp::DataFrame rcppConstructConDfAndParseTCR(Rcpp::DataFrame& data2, std::vector<std::string> uniqueData2Barcodes);
RcppExport SEXP _scRepertoire_rcppConstructConDfAndParseTCR(SEXP data2SEXP, SEXP uniqueData2BarcodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type data2(data2SEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type uniqueData2Barcodes(uniqueData2BarcodesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppConstructConDfAndParseTCR(data2, uniqueData2Barcodes));
    return rcpp_result_gen;
END_RCPP
}
// rcppConstructConDfAndParseTCRWithSeqs
Rcpp::DataFrame rcppConstructConDfAndParseTCRWithSeqs(Rcpp::DataFrame& data2, std::vector<std::string> uniqueData2Barcodes, std::vector<std::string> retainCols);
RcppExport SEXP _scRepertoire_rcppConstructConDfAndParseTCRWithSeqs(SEXP data2SEXP, SEXP uniqueData2BarcodesSEXP, SEXP retainColsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type data2(data2SEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type uniqueData2Barcodes(uniqueData2BarcodesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type retainCols(retainColsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppConstructConDfAndParseTCRWithSeqs(data2, uniqueData2Barcodes, retainCols));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scRepertoire_rcppConstructBarcodeIndex", (DL_FUNC) &_scRepertoire_rcppConstructBarcodeIndex, 2},
    {"_scRepertoire_rcppConstructConDfAndParseTCR", (DL_FUNC) &_scRepertoire_rcppConstructConDfAndParseTCR, 2},
    {"_scRepertoire_rcppConstructConDfAndParseTCRWithSeqs", (DL_FUNC) &_scRepertoire_rcppConstructConDfAndParseTCRWithSeqs, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_scRepertoire(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
